language: scala

scala:
- 2.12.6

sudo: false

script:
- sbt "++$TRAVIS_SCALA_VERSION clean" "++$TRAVIS_SCALA_VERSION test"

jdk:
- oraclejdk8

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
  - "$HOME/.sbt/launchers/"
  - "$HOME/.embedmysql/"

before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.embedmysql -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm